# import tensorflow as tf
# import numpy as np
# from keras.models import Sequential
# from keras.layers import Dense
# from tensorflow import keras
# import matplotlib.pyplot as plt
# import time
# import copy



# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.advEpsilon = QtWidgets.QLineEdit(self.centralwidget)
        self.advEpsilon.setGeometry(QtCore.QRect(80, 570, 61, 20))
        self.advEpsilon.setText("")
        self.advEpsilon.setObjectName("advEpsilon")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 570, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 600, 47, 13))
        self.label_2.setObjectName("label_2")
        self.advTile = QtWidgets.QLineEdit(self.centralwidget)
        self.advTile.setGeometry(QtCore.QRect(80, 600, 61, 20))
        self.advTile.setObjectName("advTile")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 600, 47, 13))
        self.label_3.setObjectName("label_3")
        self.streamLength = QtWidgets.QLineEdit(self.centralwidget)
        self.streamLength.setGeometry(QtCore.QRect(300, 600, 61, 20))
        self.streamLength.setObjectName("streamLength")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 40, 141, 121))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(310, 40, 141, 121))
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 47, 13))
        self.label_4.setObjectName("label_4")
        self.CELoss = QtWidgets.QLabel(self.centralwidget)
        self.CELoss.setGeometry(QtCore.QRect(30, 210, 47, 13))
        self.CELoss.setObjectName("CELoss")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 570, 47, 13))
        self.label_6.setObjectName("label_6")
        self.attackBudget = QtWidgets.QLineEdit(self.centralwidget)
        self.attackBudget.setGeometry(QtCore.QRect(300, 570, 61, 20))
        self.attackBudget.setObjectName("attackBudget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 250, 81, 16))
        self.label_7.setObjectName("label_7")
        self.secretaryStage = QtWidgets.QLabel(self.centralwidget)
        self.secretaryStage.setGeometry(QtCore.QRect(30, 280, 47, 13))
        self.secretaryStage.setObjectName("secretaryStage")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(310, 260, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(380, 570, 47, 13))
        self.label_10.setObjectName("label_10")
        self.regLoss = QtWidgets.QLineEdit(self.centralwidget)
        self.regLoss.setGeometry(QtCore.QRect(440, 570, 61, 20))
        self.regLoss.setObjectName("regLoss")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 330, 81, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(380, 600, 51, 20))
        self.label_12.setObjectName("label_12")
        self.period = QtWidgets.QLineEdit(self.centralwidget)
        self.period.setGeometry(QtCore.QRect(440, 600, 61, 20))
        self.period.setObjectName("period")
        self.lossGroup = QtWidgets.QLabel(self.centralwidget)
        self.lossGroup.setGeometry(QtCore.QRect(30, 350, 47, 13))
        self.lossGroup.setObjectName("lossGroup")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(30, 390, 81, 16))
        self.label_14.setObjectName("label_14")
        self.estimatedReg = QtWidgets.QLabel(self.centralwidget)
        self.estimatedReg.setGeometry(QtCore.QRect(30, 410, 47, 13))
        self.estimatedReg.setObjectName("estimatedReg")
        self.decision = QtWidgets.QLabel(self.centralwidget)
        self.decision.setGeometry(QtCore.QRect(310, 280, 47, 13))
        self.decision.setObjectName("decision")
        self.secretaryMemory = QtWidgets.QTextBrowser(self.centralwidget)
        self.secretaryMemory.setGeometry(QtCore.QRect(10, 520, 481, 31))
        self.secretaryMemory.setObjectName("secretaryMemory")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(200, 500, 141, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(310, 180, 101, 16))
        self.label_18.setObjectName("label_18")
        self.bestRegEstimation = QtWidgets.QLabel(self.centralwidget)
        self.bestRegEstimation.setGeometry(QtCore.QRect(310, 210, 47, 13))
        self.bestRegEstimation.setObjectName("bestRegEstimation")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(310, 330, 47, 13))
        self.label_20.setObjectName("label_20")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(310, 350, 47, 13))
        self.result.setObjectName("result")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(310, 390, 47, 13))
        self.label_22.setObjectName("label_22")
        self.foolRate = QtWidgets.QLabel(self.centralwidget)
        self.foolRate.setGeometry(QtCore.QRect(310, 410, 47, 13))
        self.foolRate.setObjectName("foolRate")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(150, 570, 61, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(160, 600, 47, 13))
        self.label_25.setObjectName("label_25")
        self.fndtile = QtWidgets.QLineEdit(self.centralwidget)
        self.fndtile.setGeometry(QtCore.QRect(220, 600, 61, 20))
        self.fndtile.setText("")
        self.fndtile.setObjectName("fndtile")
        self.fndEpsilon = QtWidgets.QLineEdit(self.centralwidget)
        self.fndEpsilon.setGeometry(QtCore.QRect(220, 570, 61, 20))
        self.fndEpsilon.setText("")
        self.fndEpsilon.setObjectName("fndEpsilon")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(50, 10, 71, 20))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(330, 10, 111, 21))
        self.label_27.setObjectName("label_27")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(310, 443, 61, 20))
        self.label_23.setObjectName("label_23")
        self.shotsLeft = QtWidgets.QLabel(self.centralwidget)
        self.shotsLeft.setGeometry(QtCore.QRect(310, 470, 47, 13))
        self.shotsLeft.setObjectName("shotsLeft")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def start(self):

        self.k=int(self.attackBudget.text())

        self.epsilon_adv=float(self.advEpsilon.text())
        self.epsilon_fnd=float(self.fndEpsilon.text())

        self.tile_fnd = int(self.fndtile.text())
        self.tile_adv = int(self.advTile.text())

        self.reg=float(self.regLoss.text())
        self.N=int(self.streamLength.text())
        self.T=float(self.period.text())

        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton.clicked.connect(self.start)

        self.label.setText(_translate("MainWindow", "epsilon_adv"))
        self.label_2.setText(_translate("MainWindow", "tile_adv"))
        self.label_3.setText(_translate("MainWindow", "N"))
        self.label_4.setText(_translate("MainWindow", "CE Loss"))
        self.CELoss.setText(_translate("MainWindow", "N/A"))
        self.label_6.setText(_translate("MainWindow", "k"))
        self.label_7.setText(_translate("MainWindow", "Secretary stage"))
        self.secretaryStage.setText(_translate("MainWindow", "N/A"))
        self.label_9.setText(_translate("MainWindow", "Decision"))
        self.label_10.setText(_translate("MainWindow", "RegLoss"))
        self.label_11.setText(_translate("MainWindow", "Loss Group"))
        self.label_12.setText(_translate("MainWindow", "Period(s)"))
        self.lossGroup.setText(_translate("MainWindow", "N/A"))
        self.label_14.setText(_translate("MainWindow", "estimated Reg"))
        self.estimatedReg.setText(_translate("MainWindow", "N/A"))
        self.decision.setText(_translate("MainWindow", "N/A"))
        self.label_17.setText(_translate("MainWindow", "Secretary memory"))
        self.label_18.setText(_translate("MainWindow", "best Reg estimated"))
        self.bestRegEstimation.setText(_translate("MainWindow", "inf"))
        self.label_20.setText(_translate("MainWindow", "Result"))
        self.result.setText(_translate("MainWindow", "N/A"))
        self.label_22.setText(_translate("MainWindow", "Fool rate"))
        self.foolRate.setText(_translate("MainWindow", "N/A"))
        self.label_24.setText(_translate("MainWindow", "epsilon_adv"))
        self.label_25.setText(_translate("MainWindow", "tile_fnd"))
        self.label_26.setText(_translate("MainWindow", "Clean image"))
        self.label_27.setText(_translate("MainWindow", "Adversarial image"))
        self.label_23.setText(_translate("MainWindow", "Shots left"))
        self.shotsLeft.setText(_translate("MainWindow", "N/A"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)


    MainWindow.show()

    sys.exit(app.exec_())
